### ISSUE TITLE
Documentation on `shallow` argument is incorrect

### ISSUE THREAD

**Issue by kryten87** [conorhastings/whitelist-object#1]
The documentation on the `shallow` argument says:

```
shallow - optional true false value. if false, will only look for whitelisted keys in top level object. defaults to false.
```

But the code says this in the `objectReducer` function:

```
if(valueIsObject(object[key]) && !shallow) {
    newObject[key] = objectReducer(object[key], whitelist, false);
}
else if(valueIsArray(object[key]) && !shallow) {
    newObject[key] = reduceArrayOfPotentialObjects(object[key], whitelist);
}
```

which recursively calls `objectReducer` on the properties of the object **when `shallow` = `false`**

The documentation seems to say that if `shallow` = `false`, then only the top-level properties will be considered, which is the opposite of what the code is doing. I think this is incorrect.

**Comment by conorhastings** [comment]
you're correct, will update, thanks for bringing this to my attention!

**Comment by kryten87** [comment]
Thanks for the quick response! And your package is just what I was looking for - I was about to write something myself, but found yours instead. Thanks!
